
replicaCount: 2

image:
  tag: 1.27.1-debian-12-r2

resources:
  requests:
    cpu: 30m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80


livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 3
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 3
  failureThreshold: 3

startupProbe:
  enabled: true
  failureThreshold: 15
  periodSeconds: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 30
  targetCPU: 30

lifecycleHook:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "echo 'Container started' >> /var/log/nginx/start.log"]
  preStop:
    exec:
      command: ["/bin/sh", "-c", "echo 'Container stopping' >> /var/log/nginx/stop.log"]
terminationGracePeriodSeconds: "30"


updateStrategy:
  type: RollingUpdate
  rollingUpdate: 
    maxSurge: 100%
    maxUnavailable: 1



ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    kubernetes.io/ingress.class: alb
  ingressClassName: alb
  pathType: Prefix
  tls: true

