name: Deployment On EKS Cluster

on: 
  push: 
     branches: ['main']
  pull_request:
     branches: ['main']   
permissions:
  id-token: write
  contents: read     

jobs:
  Deploy_On_Cluster:
    name: Deploy Application On Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3  

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.1' 
        id: install

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Update KubeConfig
        run: | 
              aws eks update-kubeconfig --region ap-northeast-2 --name spoon-test

      - name: Add and Update Helm Repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Deploy Nginx using Helm
        run: |
          helm upgrade --install test bitnami/nginx --version 18.1.11 \
            -f ./manifest/cvalues.yaml \
            --set ingress.hostname=${{ secrets.HOSTNAME }} \
            --set ingress.annotations.alb\\.ingress\\.kubernetes\\.io/certificate-arn=${{ secrets.CERTIFICATE_ARN }} \
            -n test
